[package]
name = "neofile"
version = "0.1.4"
edition = "2021"
description = "linux file command for windows. PATCH 4."
license = "GPL-3.0"
[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
tokio = { version = "1.42.0", features = ["full"] }

